scrape_configs:
  - job_name: 'web'
    dns_sd_configs:
    - names:
      - 'tasks.web'
      type: 'A'
      port: 9113

  - job_name: 'app'
    dns_sd_configs:
    - names:
      - 'tasks.app-0'
      - 'tasks.app-1'
      - 'tasks.app-2'
      type: 'A'
      port: 9113

  #- job_name: 'pgpoll'
  #  dns_sd_configs:
  #  - names:
  #    - 'tasks.pg-pool'
  #    type: 'A'
  #    port: TODO

  #- job_name: 'pg'
  #  dns_sd_configs:
  #  - names:
  #    - 'tasks.pg-0'
  #    - 'tasks.pg-1'
  #    - 'tasks.pg-2'
  #    type: 'A'
  #    port: TODO
