scrape_configs:
  - job_name: 'web'
    dns_sd_configs:
    - names:
      - 'tasks.web'
      type: 'A'
      port: 9145

  - job_name: 'app'
    dns_sd_configs:
    - names:
      - 'tasks.app-0'
      - 'tasks.app-1'
      - 'tasks.app-2'
      type: 'A'
      port: 8067
