version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    ports:
      - 9090:9090
    volumes:
       - ./prometheus-data:/prometheus/data
    #  - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.0.1
    ports:
      - 3000:3000
    volumes:
      - ./defaults.ini:/usr/share/grafana/conf/defaults.ini
    depends_on:
      - postgres

  postgres:
    image: postgres:12.3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=naoseituequesabes
