version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - ./snmp_targets.json:/etc/prometheus/snmp_targets.json

  alertmanager:
    image: prom/alertmanager:v0.20.0
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana:7.0.1
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 3000:3000
    volumes:
      - ./grafana-configs/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
    depends_on:
      - postgres

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:mm_admin_pasword@10.2.0.1:6320/postgres?sslmode=disable

  postgres:
    image: postgres:12.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=naoseituequesabes

  snmp-manager:
    build:
      context: snmp_manager/
    ports:
      - 8080:8080
    volumes:
      - ./snmp_targets.json:/app/snmp_targets.json

  snmp-exporter:
    build:
      context: snmp_exporter/
    volumes:
      - ./snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
