version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  #alertmanager:
  #  image: prom/alertmanager:v0.20.0
  #  #volumes:
  #  #  - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  #unsee:
  #  image: cloudflare/unsee:v0.9.2
  #  environment:
  #    - ALERTMANAGER_URIS=default:http://alertmanager:9093
  #  ports:
  #    - 8080:8080
  #  depends_on:
  #    - alertmanager

  grafana:
    image: grafana/grafana:7.0.1
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 3000:3000
    volumes:
      - ./grafana-configs/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
    depends_on:
      - postgres

  postgres:
    image: postgres:12.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=naoseituequesabes

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
