global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.
  evaluation_interval: 60s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'mattermost-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'swarm-prometheus'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="web"}'
        - '{job="app-0"}'
        - '{job="app-1"}'
        - '{job="app-2"}'
        - '{job="pg-poll"}'
        - '{job="pg-0"}'
        - '{job="pg-1"}'
        - '{job="pg-2"}'
    static_configs:
      - targets: ["srv2-deti.ua.pt:6330"]
